<?php
/**
 * Created by PhpStorm.
 * User: jmurray
 * Date: 12/12/16
 * Time: 11:49 AM
 */

namespace Drupal\simple_icontact\Form;


use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\simple_icontact\Service\SimpleIContactLists;
use Symfony\Component\DependencyInjection\ContainerInterface;

class SimpleIcontactListForm extends ConfigFormBase {
  /**
   * @var \Drupal\simple_icontact\Service\SimpleIContactLists
   */
  private $lists;

  protected function getEditableConfigNames() {
    return [
      'simple_icontact.config'
    ];
  }

  public function getFormId() {
    return 'simple_icontact_list_management';
  }

  public function buildForm(array $form, FormStateInterface $form_state) {
    $config = $this->config('simple_icontact.config');

    $lists = $config->get('default_lists', []);

    $available_lists = $this->lists->getLists();

    $list_options = [];

    foreach ($available_lists->lists as $key => $list) {
      $list_options[$list->listId] = $list->name;
    }

    $form['lists'] = array(
      '#type' => 'checkboxes',
      '#title' => $this->t('Select the lists to be made available to the signup form'),
      '#options' => $list_options,
      '#default_value' => $lists,
      '#required' => TRUE,
    );

    $form['refresh'] = array(
      '#type' => 'submit',
      '#title' => $this->t('Refresh Lists'),
      '#value' => 'Refresh'
    );

    return parent::buildForm($form,
      $form_state); // TODO: Change the autogenerated stub
  }

  public function submitForm(array &$form, FormStateInterface $form_state) {

    $op = $form_state->getValue('op');

    switch ($op) {
      case 'Refresh':
        $this->lists->getLists(SimpleIContactLists::REFRESH);
        break;
      default:
        $factory = \Drupal::service('config.factory');
        $config = $factory->getEditable('simple_icontact.config');

        $list_values = array_values($form_state->getValue('lists'));
        $config->set('default_lists', $list_values);

        $config->save();
        break;
    }

    parent::submitForm($form,
      $form_state); // TODO: Change the autogenerated stub
  }


  public static function create(ContainerInterface $container) {
    $config = $container->get('config.factory');
    $lists = $container->get('simple_icontact.lists');

    return new static($config, $lists);
  }

  public function __construct(
    \Drupal\Core\Config\ConfigFactoryInterface $config_factory,
    \Drupal\simple_icontact\Service\SimpleIContactLists $lists
  ) {
    parent::__construct($config_factory);
    $this->lists = $lists;
  }

}